services:
  service:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 127.0.0.1:${APP_PORT}:3000
    networks:
      - ruly_net

networks:
  ruly_net:
    driver: bridge
